# Generated by Django 5.2.5 on 2025-08-11 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peg_name', models.CharField(max_length=20)),
                ('peg_colour', models.IntegerField(choices=[(40, 'Green'), (50, 'Green Blue'), (60, 'Blue'), (70, 'Blue Black'), (80, 'Black'), (90, 'Black Red'), (100, 'Red')])),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
            ],
        ),
    ]
